export { Header as SharedHeader } from './Header'
export { Footer as SharedFooter } from './Footer'
export { Logo as SharedLogo } from './Logo'
export { Wrapper as SharedWrapper } from './Wrapper'
export { Elevate as SharedElevate } from './Elevate'
