version: 2
jobs:

  app_checkout:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build

  node_dependencies:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - run:
          name: Install Yarn
          command: |
            sudo npm install -g yarn
            sudo chmod a+x /usr/local/bin/yarn
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Installing NPM Dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - ~/build/node_modules

  testing:
      docker:
        - image: circleci/node:9-stretch-browsers
      working_directory: ~/build
      steps:
        - restore_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - restore_cache:
            key: v1-deps-{{ checksum "package.json" }}
        - run:
            name: Performing Tests
            command: yarn test

  precompile:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - run:
          name: Install Yarn
          command: |
            sudo npm install -g yarn
            sudo chmod a+x /usr/local/bin/yarn
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Compiling App
          command: yarn build:dist
      - save_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build/public

  deploy:
    docker:
      - image: circleci/node:9-stretch-browsers
    working_directory: ~/build
    steps:
      - restore_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install python-pip python-dev jq
            sudo pip install awscli
      - run:
          name: Deploy to S3 if tests pass
          command: aws s3 sync public s3://www.hilaryosborne.com --delete

workflows:
  version: 2
  build_and_test:
    jobs:
      - app_checkout
      - node_dependencies:
          requires:
            - app_checkout
      - testing:
          requires:
            - app_checkout
      - precompile:
          requires:
            - testing
            - node_dependencies
      - deploy:
          requires:
            - precompile