version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch-browsers
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build:dist
  test:
    docker:
      - image: circleci/node:9-stretch-browsers
    steps:
      - checkout
      - run: yarn test